// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAILQR1fe90NztE2CTDG-d14OMXnBmXg0',
    appId: '1:866705337726:web:304b0a35c2d8ffdf44972f',
    messagingSenderId: '866705337726',
    projectId: 'quizzolino',
    authDomain: 'quizzolino.firebaseapp.com',
    storageBucket: 'quizzolino.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGRqz7VBaHJHylcjjqR2Jq2nuo8ibuNU',
    appId: '1:866705337726:android:6d958ddd8753e45444972f',
    messagingSenderId: '866705337726',
    projectId: 'quizzolino',
    storageBucket: 'quizzolino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmVOb9bQgYjDwzoZpulZX3m7oFPhHwy0',
    appId: '1:866705337726:ios:d13c9ecc2216b11244972f',
    messagingSenderId: '866705337726',
    projectId: 'quizzolino',
    storageBucket: 'quizzolino.appspot.com',
    iosBundleId: 'com.example.quizzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmVOb9bQgYjDwzoZpulZX3m7oFPhHwy0',
    appId: '1:866705337726:ios:d13c9ecc2216b11244972f',
    messagingSenderId: '866705337726',
    projectId: 'quizzolino',
    storageBucket: 'quizzolino.appspot.com',
    iosBundleId: 'com.example.quizzo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAILQR1fe90NztE2CTDG-d14OMXnBmXg0',
    appId: '1:866705337726:web:032549604b7b14a744972f',
    messagingSenderId: '866705337726',
    projectId: 'quizzolino',
    authDomain: 'quizzolino.firebaseapp.com',
    storageBucket: 'quizzolino.appspot.com',
  );
}
